---
## Proxmox
  - name: Proxmox Hypervisor
    set_fact:
      type: p
      type_desc: "proxmox {{ ansible_distribution }}"
    when: '"pve" in ansible_kernel'

## Raspberry
  - name: Raspberry
    set_fact:
      type: r
      type_desc: "{{ ansible_distribution }} Raspberry"
    when: '"raspi" in ansible_kernel'

## Generic
  - name: Generic
    set_fact:
      type: g
      type_desc: "Generic {{ ansible_distribution }}"
    when: 
      - '"raspi" not in ansible_kernel'
      - '"pve" not in ansible_kernel'
      