---
# - name: Memory classification
#   include: memory.yml

- name: Set ansible_fqdn
  set_fact:
    ansible_fqdn: "{{ ansible_hostname }}.{{ ansible_dns.search[0] }}"

- name: Generate all *-map.yml files
  ansible.builtin.template:
    src: "../templates/{{ item }}-map.j2"
    dest: "{{ item }}-map.yml"
  delegate_to: 127.0.0.1
  run_once: yes
  loop:
    - memory-size
    - kernel-type

- name: Processing dynamic maps
  include: "{{ item }}-map.yml"
  loop:
    - memory-size
    - kernel-type

- name: cleanup dynamic_size_map
  ansible.builtin.file:
    path: "{{ item }}-map.yml"
    state: absent
  delegate_to: 127.0.0.1
  run_once: yes
  loop:
    - memory-size
    - kernel-type