---
  - name: Memory classification
    include: memory.yml

  - name: Kernel classification
    include: kernel.yml

  # - name: CPU classification
  #   include: cpu.yml

  - name: Classification
    set_fact:
      classification: "{{ type }}{{ ansible_processor_vcpus }}.{{ size }}"