---
# - name: Memory classification
#   include: memory.yml

- name: Set ansible_fqdn
  set_fact:
    ansible_fqdn: "{{ ansible_hostname }}.{{ ansible_dns.search[0] }}"

- name: Generate all *-map.yml files
  ansible.builtin.template:
    src: "../templates/{{ item }}-map.j2"
    dest: "{{ item }}-map.yml"
  delegate_to: 127.0.0.1
  run_once: yes
  loop:
    - memory-size
    - kernel-type

- name: Processing dynamic maps
  include_tasks: "{{ item }}-map.yml"
  loop:
    - memory-size
    - kernel-type

- name: cleanup dynamic_size_map
  ansible.builtin.file:
    path: "{{ item }}-map.yml"
    state: absent
  delegate_to: 127.0.0.1
  run_once: yes
  loop:
    - memory-size
    - kernel-type

- name: Set classification facts
  set_fact:
    classify_facts:
      class: "{{type}}{{ ansible_processor_cores }}.{{ size }}"
      desc: "{{ type_desc }}"
      arch: "{{ ansible_architecture }}"
      size: "{{ size }}"
      type: "{{ type }}"
      cores: "{{ ansible_processor_cores }}"
      vcpus: "{{ ansible_processor_vcpus }}"
      memory: "{{ ansible_memtotal_mb }}mb"
